title: Vantaca IQ Documentation
description: Support documentation for Vantaca IQ
theme: just-the-docs

url: https://gifmackenzie.github.io/IQHelp

nav_external_links:
   - title: Vantaca IQ
     url: iq.vantaca.net

$link-color: $blue-100;

search_enabled: true
search.button: true