title: Vantaca IQ Documentation
description: Support documentation for Vantaca IQ
theme: just-the-docs

url: https://gifmackenzie.github.io/IQHelp


logo: "/assets/images/VantacaLogo-New-Final_Horizontal"

aux_links:
  "Vantaca IQ": 
  - "https://iq.vantaca.net"



$link-color: $blue-100;

search_enabled: true
search.button: true