title: Vantaca IQ Documentation
description: Support documentation for Vantaca IQ
theme: just-the-docs
logo: "/assets/images/VantacaLogo.png"
url: https://gifmackenzie.github.io/IQHelp

markdown: kramdown

favicon_ico: "/assets/images/favicon.ico"

aux_links:
  "Vantaca IQ": 
  - "https://iq.vantaca.net"

color_scheme: dark


$link-color: $blue-100;

search_enabled: true
search.button: true