title: Vantaca IQ Documentation
description: Support documentation for Vantaca IQ
theme: just-the-docs

url: https://gifmackenzie.github.io/IQHelp

aux_links:
  Template Repository: https://github.com/gifmackenzie/IQHelp

$link-color: $blue-100;

search_enabled: true
search.button: true